import SwiftUI

// MARK: - Shared Date Formatter

extension DateFormatter {
    /// App-wide display format: DD/MM/YYYY
    static let display: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "dd/MM/yyyy"
        return f
    }()
}

// MARK: - Language Enum

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case german = "de"

    var id: String { rawValue }
    var displayName: String {
            switch self {
            case .english: return "EN"
            case .german:  return "DE"
            }
        }
    var flag: String {
        switch self {
        case .english: return "🇬🇧"
        case .german:  return "🇦🇹"
        }
    }
}

// MARK: - Localization Manager

@Observable
final class LocalizationManager {
    var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: "appLanguage") }
    }

    init() {
        let saved = UserDefaults.standard.string(forKey: "appLanguage") ?? "en"
        self.language = AppLanguage(rawValue: saved) ?? .english
    }

    /// Main lookup function
    func t(_ key: String) -> String {
        let table = language == .german ? Self.de : Self.en
        return table[key] ?? key
    }

    // MARK: - English Strings

    static let en: [String: String] = [
        // Navigation
        "nav.dashboard": "Dashboard",
        "nav.apartments": "Apartments",
        "nav.contracts": "Contracts",
        "nav.tenants": "Tenants",
        "nav.rents": "Rent Tracking",
        "nav.settings": "Settings",
        "nav.property": "Property",

        // Company
        "company.title": "Company",
        "company.all": "All Companies",
        "company.1111immo": "1111 Immobilien",
        "company.1111holding": "1111 Holding",
        "company.sherman": "Sherman Immobilien",
        "company.privat": "Private",

        // Common
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.add": "Add",
        "common.close": "Close",
        "common.search": "Search",
        "common.notes": "Notes",
        "common.all": "All",
        "common.none": "None",
        "common.yes": "Yes",
        "common.no": "No",
        "common.done": "Done",
        "common.select_all": "Select All",
        "common.deselect_all": "Deselect All",
        "common.open": "Open",
        "common.remove": "Remove",
        "common.attach": "Attach",
        "common.export": "Export",
        "common.showing_x_of_y": "Showing %d of %d",
        "common.per_month": "/mo",
        "common.rooms": "rooms",
        "common.email": "Email",
        "common.phone": "Phone",
        "common.id_passport": "ID/Passport",

        // Apartments
        "apt.title": "Apartments",
        "apt.add": "Add Apartment",
        "apt.edit": "Edit Apartment",
        "apt.search": "Search apartments…",
        "apt.no_selection": "No Apartment Selected",
        "apt.no_selection_desc": "Select an apartment, add a new one, or import from CSV.",
        "apt.select_hint": "Click the circles next to apartments to select them.",
        "apt.units": "units",
        "apt.unit": "unit",
        "apt.delete_confirm": "Delete %@?",
        "apt.delete_msg": "All associated contracts and payments will also be deleted.",
        "apt.bulk_delete": "Delete %d apartments?",
        "apt.bulk_delete_msg": "Deletes %d apartments plus all linked contracts and payments.",
        "apt.type": "Type",
        "apt.type.standard": "Standard Apartment",
        "apt.type.wg": "Shared Apartment (WG)",
        "apt.status": "Status",
        "apt.status.available": "Available",
        "apt.status.rented": "Rented",
        "apt.status.maintenance": "Maintenance",
        "apt.status.reserved": "Reserved",
        "apt.address": "Address",
        "apt.street": "Street & number",
        "apt.gate": "Stiege / Gate (optional)",
        "apt.apt_number": "Top / Apt. number (optional)",
        "apt.postal": "Postal code",
        "apt.city": "City",
        "apt.country": "Country",
        "apt.details": "Details",
        "apt.floor": "Floor",
        "apt.rooms": "Rooms",
        "apt.bathrooms": "Bathrooms",
        "apt.area": "Area (m²)",
        "apt.rent": "Monthly Rent (€)",
        "apt.rent_section": "Rent",
        "apt.max_tenants": "Max Tenants",
        "apt.active_tenants": "Active Tenants",
        "apt.current_tenant": "Current Tenant",
        "apt.wg_tenants": "WG Tenants",
        "apt.no_tenants": "No active tenant in this apartment.",
        "apt.no_tenants_wg": "No tenants currently registered in this WG.",
        "apt.all_contracts": "All Contracts",
        "apt.monthly_rent": "Monthly Rent",
        "apt.contracts_count": "Contracts",
        "apt.import": "Import from CSV / Excel",
        "apt.select_mode": "Select multiple",
        "apt.display_name": "Display name",

        // Tenants
        "tenant.title": "Tenants",
        "tenant.add": "Register Tenant",
        "tenant.edit": "Edit Tenant",
        "tenant.search": "Search tenants…",
        "tenant.no_selection": "No Tenant Selected",
        "tenant.no_selection_desc": "Select a tenant from the list or register a new one.",
        "tenant.delete_confirm": "Delete %@?",
        "tenant.delete_msg": "The tenant's active contracts will be terminated and their contract links removed.",
        "tenant.personal_info": "Personal Information",
        "tenant.first_name": "First name",
        "tenant.last_name": "Last name",
        "tenant.email": "Email address",
        "tenant.phone": "Phone number",
        "tenant.id_passport": "ID / Passport number",
        "tenant.id_passport_short": "ID / Passport",
        "tenant.tenant_number": "Tenant No.",
        "tenant.tenant_number_field": "Tenant number (e.g. M-001)",
        "tenant.tenant_number_help": "Used to identify this tenant in rent payment records and bookkeeping exports.",
        "tenant.rent_ref": "Rent Transaction Reference",
        "tenant.id_document": "ID Document",
        "tenant.no_id_doc": "No ID document attached",
        "tenant.no_id_doc_desc": "Attach a photo or PDF of the tenant's ID, passport, or residence permit.",
        "tenant.attach_doc": "Attach Document",
        "tenant.attach_doc_help": "Attach an ID document to this tenant",
        "tenant.attach_failed": "Failed to attach document:",
        "tenant.attach_id": "Attach ID",
        "tenant.remove_doc_confirm": "Remove attached ID document?",
        "tenant.remove_doc_msg": "The file will be deleted from ~/Documents/PropertyManager/TenantDocs/. This cannot be undone.",
        "tenant.register": "Register",
        "tenant.archive": "Archive Tenant",
        "tenant.archive_confirm": "Archive %@?",
        "tenant.archive_msg": "The tenant will be archived and their active contracts terminated. Data is preserved.",
        "tenant.bulk_archive": "Archive %d tenants?",
        "tenant.bulk_archive_msg": "Selected tenants will be archived and their active contracts terminated.",
        "tenant.bulk_delete": "Delete %d tenants?",
        "tenant.bulk_delete_msg": "This cannot be undone. ID documents and contract links will be removed.",
        "tenant.show_archived": "Show Archived",
        "tenant.archived_badge": "Archived",
        "tenant.select_mode": "Select",

        // Contracts
        "contract.title": "Contracts",
        "contract.add": "New Contract",
        "contract.edit": "Edit Contract",
        "contract.search": "Search contracts…",
        "contract.no_selection": "No Contract Selected",
        "contract.no_selection_desc": "Select a contract from the list or add a new one.",
        "contract.delete_confirm": "Delete contract %@?",
        "contract.delete_msg": "All associated payment records will also be deleted.",
        "contract.number": "Contract number",
        "contract.type": "Type",
        "contract.category": "Category",
        "contract.category.mietvertrag": "Rental Agreement",
        "contract.category.verwaltungsvertrag": "Management Agreement",
        "contract.all_categories": "All Categories",
        "contract.status": "Status",
        "contract.status.active": "Active",
        "contract.status.pending": "Pending",
        "contract.status.expired": "Expired",
        "contract.status.terminated": "Terminated",
        "contract.dates": "Dates",
        "contract.start": "Start Date",
        "contract.end": "End Date",
        "contract.financials": "Financials",
        "contract.monthly_rent": "Monthly Rent (€)",
        "contract.deposit": "Deposit (€)",
        "contract.due_day": "Payment Due Day",
        "contract.duration": "Duration",
        "contract.months": "months",
        "contract.link_apartment": "Link Apartment",
        "contract.link_tenant": "Link Tenant",
        "contract.apartment": "Apartment",
        "contract.tenant": "Tenant",
        "contract.pdf": "Contract PDF",
        "contract.no_pdf": "No PDF attached",
        "contract.no_pdf_desc": "Attach a signed contract PDF to keep it linked to this record.",
        "contract.attach_pdf": "Attach PDF",
        "contract.attach_pdf_help": "Attach a PDF to this contract",
        "contract.attach_failed": "Failed to attach PDF:",
        "contract.remove_pdf_confirm": "Remove attached PDF?",
        "contract.remove_pdf_msg": "The file will be deleted from ~/Documents/PropertyManager/Contracts/. This cannot be undone.",
        "contract.linked_apartment": "Linked Apartment",
        "contract.linked_tenant": "Linked Tenant",
        "contract.period": "Contract Period",
        "contract.expiring_soon": "Expiring within 60 days",
        "contract.payment_history": "Payment History",
        "contract.show_finder": "Show in Finder",
        "contract.all_types": "All Types",
        "contract.all_status": "All Status",
        "contract.terminate": "Terminate Contract",
        "contract.terminate_confirm": "Terminate %@?",
        "contract.terminate_msg": "The contract will be marked as terminated. Payment history is preserved.",
        "contract.bulk_terminate": "Terminate %d contracts?",
        "contract.bulk_terminate_msg": "Selected contracts will be marked as terminated.",
        "contract.bulk_delete": "Delete %d contracts?",
        "contract.bulk_delete_msg": "This cannot be undone. Payment history will also be deleted.",
        "contract.show_terminated": "Show Terminated",
        "contract.select_mode": "Select",

        // Rents
        "rent.title": "Rent Tracking",
        "rent.add": "Record Payment",
        "rent.edit": "Edit Payment",
        "rent.payments": "Payments",
        "rent.no_payments": "No Payments",
        "rent.no_payments_desc": "No payment records found for the current filters.",
        "rent.delete_confirm": "Delete this payment?",
        "rent.delete_msg": "This payment record will be permanently deleted.",
        "rent.mark_paid": "Mark Paid",
        "rent.direction": "Direction",
        "rent.income": "Income",
        "rent.expense": "Expense",
        "rent.select_mode": "Select",
        "rent.bulk_delete": "Delete %d payments?",
        "rent.bulk_delete_msg": "These payment records will be permanently deleted.",
        "rent.monthly_overview": "Monthly Overview",
        "rent.no_data": "No payment data",
        "rent.filter_contract": "Filter by Contract",
        "rent.filter_status": "Filter by Status",
        "rent.all_contracts": "All Contracts",
        "rent.select_contract": "Select contract",
        "rent.contract_section": "Contract",
        "rent.period": "Period",
        "rent.month": "Month",
        "rent.year": "Year",
        "rent.due_date": "Due Date",
        "rent.payment_section": "Payment",
        "rent.amount": "Amount (€)",
        "rent.status": "Status",
        "rent.amount_paid": "Amount Paid (€)",
        "rent.record_paid_date": "Record paid date",
        "rent.paid_on": "Paid On",
        "rent.status.paid": "Paid",
        "rent.status.pending": "Pending",
        "rent.status.overdue": "Overdue",
        "rent.status.partial": "Partial",
        "rent.record": "Record",
        "rent.total_received": "Total received",

        // Payment history in apartment
        "apt.payment_history": "Payment History",

        // Export
        "export.title": "Export Report",
        "export.report_type": "Report Type",
        "export.date_range": "Date Range",
        "export.from": "From",
        "export.to": "To",
        "export.filters": "Filters",
        "export.all_apartments": "All Apartments",
        "export.all_statuses": "All Statuses",
        "export.format": "Format",
        "export.preview": "Preview",
        "export.export_file": "Export to File",
        "export.no_data": "No data to export.",
        "export.export_failed": "Export failed:",
        "export.success": "Exported %d rows to %@",
        "export.payment_records": "payment records",
        "export.more_rows": "more rows",
        "export.type.payments": "Rent Payments",
        "export.type.tenant_ledger": "Tenant Ledger",
        "export.type.apartment_summary": "Apartment Summary",
        "export.type.contract_overview": "Contract Overview",

        // Export CSV headers
        "export.h.month": "Month",
        "export.h.year": "Year",
        "export.h.tenant": "Tenant",
        "export.h.tenant_no": "Tenant No.",
        "export.h.apartment": "Apartment",
        "export.h.contract": "Contract",
        "export.h.amount_due": "Amount Due",
        "export.h.amount_paid": "Amount Paid",
        "export.h.status": "Status",
        "export.h.due_date": "Due Date",
        "export.h.paid_date": "Paid Date",
        "export.h.notes": "Notes",
        "export.h.total_due": "Total Due",
        "export.h.total_paid": "Total Paid",
        "export.h.balance": "Balance",
        "export.h.paid_count": "Paid Count",
        "export.h.pending_count": "Pending Count",
        "export.h.overdue_count": "Overdue Count",
        "export.h.street": "Street",
        "export.h.gate": "Gate",
        "export.h.top": "Top",
        "export.h.city": "City",
        "export.h.postal": "Postal Code",
        "export.h.type": "Type",
        "export.h.company": "Company",
        "export.h.category": "Category",
        "export.h.direction": "Direction",
        "export.h.rooms": "Rooms",
        "export.h.area": "Area (m2)",
        "export.h.monthly_rent": "Monthly Rent",
        "export.h.active_tenants": "Active Tenants",
        "export.h.total_contracts": "Total Contracts",
        "export.h.total_received": "Total Payments Received",
        "export.h.contract_no": "Contract No.",
        "export.h.start_date": "Start Date",
        "export.h.end_date": "End Date",
        "export.h.deposit": "Deposit",
        "export.h.duration": "Duration (months)",
        "export.h.payments_count": "Payments Count",
        "export.h.has_pdf": "Has PDF",

        // Dashboard
        "dash.title": "Dashboard",
        "dash.overview": "Overview",
        "dash.total_apartments": "Total Apartments",
        "dash.active_contracts": "Active Contracts",
        "dash.total_tenants": "Total Tenants",
        "dash.monthly_revenue": "Monthly Revenue",
        "dash.revenue_chart": "Revenue (Last 6 Months)",
        "dash.expiring_contracts": "Expiring Contracts",
        "dash.no_expiring": "No contracts expiring soon.",
        "dash.recent_payments": "Recent Payments",
        "dash.no_payments": "No recent payment activity.",
        "dash.occupancy": "Occupancy Rate",
        "dash.no_apartments": "No apartments yet",
        "dash.no_apartments_desc": "Register apartments to see their status breakdown.",
        "dash.alerts": "Alerts & Follow-Ups",
        "dash.company_performance": "Company Performance",
        "dash.company_revenue": "%@ Revenue (Last 12 Months)",
        "dash.contract_expires": "Contract %@ for %@ expires on %@",
        "dash.overdue_payment": "Overdue payment of %@ for %@",

        // Settings
        "settings.title": "Settings",
        "settings.users": "User Management",
        "settings.add_user": "Add User",
        "settings.edit_user": "Edit User",
        "settings.delete_user": "Delete User",
        "settings.change_password": "Change Password",
        "settings.username": "Username",
        "settings.full_name": "Full Name",
        "settings.role": "Role",
        "settings.password": "Password",
        "settings.new_password": "New Password",
        "settings.confirm_password": "Confirm Password",
        "settings.language": "Language",
        "settings.manage_access": "Manage who can access this app.",
        "settings.select_user": "Select a user to view details",
        "settings.you": "(You)",
        "settings.role_permissions": "Role & Permissions",
        "settings.can_manage": "Can manage",
        "settings.member_since": "Member since",
        "settings.access_summary": "Access Summary",
        "settings.identity": "Identity",
        "settings.full_name_req": "Full name *",
        "settings.username_req": "Username *",
        "settings.password_req": "Password *",
        "settings.current_password": "Current Password",
        "settings.current_password_field": "Current password",
        "settings.confirm_new": "Confirm new password",
        "settings.no_match": "Passwords do not match",
        "settings.wrong_password": "Current password is incorrect.",
        "settings.update": "Update",
        "settings.cannot_delete": "Cannot Delete",
        "settings.cannot_undo": "This cannot be undone.",
        "settings.last_admin": "This is the last admin user. Promote another user to admin before deleting this one.",
        "settings.perm.everything": "Everything",
        "settings.perm.apt_con_ten_pay": "Apartments, Contracts, Tenants, Payments",
        "settings.perm.payments_only": "Payments only",
        "settings.perm.manage_users": "Manage Users",
        "settings.perm.manage_apartments": "Manage Apartments",
        "settings.perm.manage_contracts": "Manage Contracts",
        "settings.perm.manage_tenants": "Manage Tenants",
        "settings.perm.manage_payments": "Manage Payments",

        // CSV Import
        "csv.title": "Import from CSV / Excel",
        "csv.company": "Company",
        "csv.apt_columns": "Apartment columns",
        "csv.tenant_columns": "Tenant Columns",
        "csv.tenant_columns_desc": "Tenant columns (optional — will be created and linked automatically)",
        "csv.required_note": "Only **street** is required. If tenant columns are present, a tenant and active contract are auto-created.",
        "csv.defaults": "Defaults for missing values",
        "csv.import_tenants": "Import tenants from CSV and link to apartments",
        "csv.choose_file": "Choose CSV File…",
        "csv.download_sample": "Download Sample CSV",
        "csv.change_file": "Change File",
        "csv.rows_found": "rows found",
        "csv.delimiter": "delimiter",
        "csv.import_now": "Import Now",
        "csv.import_complete": "Import Complete",
        "csv.apartments_imported": "apartments imported",
        "csv.tenants_imported": "tenants with contracts created",
        "csv.import_another": "Import Another",
        "csv.preview": "Preview",
        "csv.panel_message": "Choose a CSV exported from Excel",
        "csv.panel_prompt": "Import",
        "csv.error.read": "Could not read file. Try saving as UTF-8 CSV from Excel.",
        "csv.error.empty": "File appears empty.",
        "csv.error.rows": "CSV needs at least a header row and one data row.",
        "csv.duplicates_skipped": "%d duplicates skipped",
        "csv.duplicate_skip": "Skip",
        "csv.duplicate_update": "Update",
        "csv.resolve_duplicates": "Resolve Duplicates",
        "csv.skip_all": "Skip All",
        "csv.update_all": "Update All",
        "csv.conflict_count": "%d duplicate(s) found",
        "csv.confirm_import": "Confirm Import",
        "csv.contract_category": "Contract Type",

        // Sync
        "settings.sync": "Sync",
        "settings.sync.active": "iCloud sync active",
        "settings.sync.inactive": "iCloud not available",
        "settings.sync.location": "Store location",

        // Login
        "login.title": "Property Manager",
        "login.subtitle": "Sign in to manage your properties",
        "login.username": "Username",
        "login.password": "Password",
        "login.sign_in": "Sign In",
        "login.invalid": "Invalid username or password.",
        "login.sign_out": "Sign Out",
        "login.default_creds": "Default credentials: admin / admin123",
    ]

    // MARK: - German Strings

    static let de: [String: String] = [
        // Navigation
        "nav.dashboard": "Übersicht",
        "nav.apartments": "Wohnungen",
        "nav.contracts": "Verträge",
        "nav.tenants": "Mieter",
        "nav.rents": "Mietverwaltung",
        "nav.settings": "Einstellungen",
        "nav.property": "Immobilien",

        // Common
        // Company
        "company.title": "Unternehmen",
        "company.all": "Alle Unternehmen",
        "company.1111immo": "1111 Immobilien",
        "company.1111holding": "1111 Holding",
        "company.sherman": "Sherman Immobilien",
        "company.privat": "Privat",

        "common.save": "Speichern",
        "common.cancel": "Abbrechen",
        "common.delete": "Löschen",
        "common.edit": "Bearbeiten",
        "common.add": "Hinzufügen",
        "common.close": "Schließen",
        "common.search": "Suchen",
        "common.notes": "Notizen",
        "common.all": "Alle",
        "common.none": "Keine",
        "common.yes": "Ja",
        "common.no": "Nein",
        "common.done": "Fertig",
        "common.select_all": "Alle auswählen",
        "common.deselect_all": "Auswahl aufheben",
        "common.open": "Öffnen",
        "common.remove": "Entfernen",
        "common.attach": "Anhängen",
        "common.export": "Exportieren",
        "common.showing_x_of_y": "Zeige %d von %d",
        "common.per_month": "/Monat",
        "common.rooms": "Zimmer",
        "common.email": "E-Mail",
        "common.phone": "Telefon",
        "common.id_passport": "Ausweis/Reisepass",

        // Apartments
        "apt.title": "Wohnungen",
        "apt.add": "Wohnung hinzufügen",
        "apt.edit": "Wohnung bearbeiten",
        "apt.search": "Wohnungen suchen…",
        "apt.no_selection": "Keine Wohnung ausgewählt",
        "apt.no_selection_desc": "Wählen Sie eine Wohnung aus, fügen Sie eine neue hinzu oder importieren Sie aus CSV.",
        "apt.select_hint": "Klicken Sie auf die Kreise neben den Wohnungen, um sie auszuwählen.",
        "apt.units": "Einheiten",
        "apt.unit": "Einheit",
        "apt.delete_confirm": "%@ löschen?",
        "apt.delete_msg": "Alle zugehörigen Verträge und Zahlungen werden ebenfalls gelöscht.",
        "apt.bulk_delete": "%d Wohnungen löschen?",
        "apt.bulk_delete_msg": "Löscht %d Wohnungen samt aller verknüpften Verträge und Zahlungen.",
        "apt.type": "Typ",
        "apt.type.standard": "Standardwohnung",
        "apt.type.wg": "Wohngemeinschaft (WG)",
        "apt.status": "Status",
        "apt.status.available": "Verfügbar",
        "apt.status.rented": "Vermietet",
        "apt.status.maintenance": "Wartung",
        "apt.status.reserved": "Reserviert",
        "apt.address": "Adresse",
        "apt.street": "Straße & Nummer",
        "apt.gate": "Stiege / Eingang (optional)",
        "apt.apt_number": "Top / Wohnungsnr. (optional)",
        "apt.postal": "Postleitzahl",
        "apt.city": "Stadt",
        "apt.country": "Land",
        "apt.details": "Details",
        "apt.floor": "Stockwerk",
        "apt.rooms": "Zimmer",
        "apt.bathrooms": "Badezimmer",
        "apt.area": "Fläche (m²)",
        "apt.rent": "Monatsmiete (€)",
        "apt.rent_section": "Miete",
        "apt.max_tenants": "Max. Mieter",
        "apt.active_tenants": "Aktive Mieter",
        "apt.current_tenant": "Aktueller Mieter",
        "apt.wg_tenants": "WG-Mieter",
        "apt.no_tenants": "Kein aktiver Mieter in dieser Wohnung.",
        "apt.no_tenants_wg": "Keine Mieter derzeit in dieser WG registriert.",
        "apt.all_contracts": "Alle Verträge",
        "apt.monthly_rent": "Monatsmiete",
        "apt.contracts_count": "Verträge",
        "apt.import": "Aus CSV / Excel importieren",
        "apt.select_mode": "Mehrfachauswahl",
        "apt.display_name": "Anzeigename",

        // Tenants
        "tenant.title": "Mieter",
        "tenant.add": "Mieter registrieren",
        "tenant.edit": "Mieter bearbeiten",
        "tenant.search": "Mieter suchen…",
        "tenant.no_selection": "Kein Mieter ausgewählt",
        "tenant.no_selection_desc": "Wählen Sie einen Mieter aus der Liste oder registrieren Sie einen neuen.",
        "tenant.delete_confirm": "%@ löschen?",
        "tenant.delete_msg": "Die aktiven Verträge des Mieters werden gekündigt und die Verknüpfungen entfernt.",
        "tenant.personal_info": "Persönliche Daten",
        "tenant.first_name": "Vorname",
        "tenant.last_name": "Nachname",
        "tenant.email": "E-Mail-Adresse",
        "tenant.phone": "Telefonnummer",
        "tenant.id_passport": "Ausweis- / Reisepassnummer",
        "tenant.id_passport_short": "Ausweis / Reisepass",
        "tenant.tenant_number": "Mieter-Nr.",
        "tenant.tenant_number_field": "Mieternummer (z.B. M-001)",
        "tenant.tenant_number_help": "Zur Identifikation des Mieters in Mietzahlungen und Buchhaltungsexporten.",
        "tenant.rent_ref": "Zahlungsreferenz",
        "tenant.id_document": "Ausweisdokument",
        "tenant.no_id_doc": "Kein Ausweisdokument angehängt",
        "tenant.no_id_doc_desc": "Foto oder PDF des Ausweises, Reisepasses oder Aufenthaltstitels anhängen.",
        "tenant.attach_doc": "Dokument anhängen",
        "tenant.attach_doc_help": "Ein Ausweisdokument an diesen Mieter anhängen",
        "tenant.attach_failed": "Dokument konnte nicht angehängt werden:",
        "tenant.attach_id": "Ausweis anhängen",
        "tenant.remove_doc_confirm": "Angehängtes Dokument entfernen?",
        "tenant.remove_doc_msg": "Die Datei wird aus ~/Documents/PropertyManager/TenantDocs/ gelöscht. Dies kann nicht rückgängig gemacht werden.",
        "tenant.register": "Registrieren",
        "tenant.archive": "Mieter archivieren",
        "tenant.archive_confirm": "%@ archivieren?",
        "tenant.archive_msg": "Der Mieter wird archiviert und aktive Verträge werden gekündigt. Daten bleiben erhalten.",
        "tenant.bulk_archive": "%d Mieter archivieren?",
        "tenant.bulk_archive_msg": "Ausgewählte Mieter werden archiviert und ihre aktiven Verträge gekündigt.",
        "tenant.bulk_delete": "%d Mieter löschen?",
        "tenant.bulk_delete_msg": "Dies kann nicht rückgängig gemacht werden. Ausweisdokumente und Vertragsverknüpfungen werden entfernt.",
        "tenant.show_archived": "Archivierte anzeigen",
        "tenant.archived_badge": "Archiviert",
        "tenant.select_mode": "Auswählen",

        // Contracts
        "contract.title": "Verträge",
        "contract.add": "Neuer Vertrag",
        "contract.edit": "Vertrag bearbeiten",
        "contract.search": "Verträge suchen…",
        "contract.no_selection": "Kein Vertrag ausgewählt",
        "contract.no_selection_desc": "Wählen Sie einen Vertrag aus der Liste oder erstellen Sie einen neuen.",
        "contract.delete_confirm": "Vertrag %@ löschen?",
        "contract.delete_msg": "Alle zugehörigen Zahlungseinträge werden ebenfalls gelöscht.",
        "contract.number": "Vertragsnummer",
        "contract.type": "Typ",
        "contract.category": "Kategorie",
        "contract.category.mietvertrag": "Mietvertrag",
        "contract.category.verwaltungsvertrag": "Verwaltungsvertrag",
        "contract.all_categories": "Alle Kategorien",
        "contract.status": "Status",
        "contract.status.active": "Aktiv",
        "contract.status.pending": "Ausstehend",
        "contract.status.expired": "Abgelaufen",
        "contract.status.terminated": "Gekündigt",
        "contract.dates": "Daten",
        "contract.start": "Vertragsbeginn",
        "contract.end": "Vertragsende",
        "contract.financials": "Finanzen",
        "contract.monthly_rent": "Monatsmiete (€)",
        "contract.deposit": "Kaution (€)",
        "contract.due_day": "Fälligkeitstag",
        "contract.duration": "Laufzeit",
        "contract.months": "Monate",
        "contract.link_apartment": "Wohnung verknüpfen",
        "contract.link_tenant": "Mieter verknüpfen",
        "contract.apartment": "Wohnung",
        "contract.tenant": "Mieter",
        "contract.pdf": "Vertrags-PDF",
        "contract.no_pdf": "Kein PDF angehängt",
        "contract.no_pdf_desc": "Hängen Sie ein unterschriebenes Vertrags-PDF an, um es mit diesem Datensatz zu verknüpfen.",
        "contract.attach_pdf": "PDF anhängen",
        "contract.attach_pdf_help": "Ein PDF an diesen Vertrag anhängen",
        "contract.attach_failed": "PDF konnte nicht angehängt werden:",
        "contract.remove_pdf_confirm": "Angehängtes PDF entfernen?",
        "contract.remove_pdf_msg": "Die Datei wird aus ~/Documents/PropertyManager/Contracts/ gelöscht. Dies kann nicht rückgängig gemacht werden.",
        "contract.linked_apartment": "Verknüpfte Wohnung",
        "contract.linked_tenant": "Verknüpfter Mieter",
        "contract.period": "Vertragszeitraum",
        "contract.expiring_soon": "Läuft innerhalb von 60 Tagen ab",
        "contract.payment_history": "Zahlungsverlauf",
        "contract.show_finder": "Im Finder anzeigen",
        "contract.all_types": "Alle Typen",
        "contract.all_status": "Alle Status",
        "contract.terminate": "Vertrag kündigen",
        "contract.terminate_confirm": "%@ kündigen?",
        "contract.terminate_msg": "Der Vertrag wird als gekündigt markiert. Zahlungshistorie bleibt erhalten.",
        "contract.bulk_terminate": "%d Verträge kündigen?",
        "contract.bulk_terminate_msg": "Ausgewählte Verträge werden als gekündigt markiert.",
        "contract.bulk_delete": "%d Verträge löschen?",
        "contract.bulk_delete_msg": "Dies kann nicht rückgängig gemacht werden. Zahlungshistorie wird ebenfalls gelöscht.",
        "contract.show_terminated": "Gekündigte anzeigen",
        "contract.select_mode": "Auswählen",

        // Rents
        "rent.title": "Mietverwaltung",
        "rent.add": "Zahlung erfassen",
        "rent.edit": "Zahlung bearbeiten",
        "rent.payments": "Zahlungen",
        "rent.no_payments": "Keine Zahlungen",
        "rent.no_payments_desc": "Keine Zahlungseinträge für die aktuellen Filter gefunden.",
        "rent.delete_confirm": "Diese Zahlung löschen?",
        "rent.delete_msg": "Dieser Zahlungseintrag wird dauerhaft gelöscht.",
        "rent.mark_paid": "Als bezahlt",
        "rent.direction": "Richtung",
        "rent.income": "Einnahme",
        "rent.expense": "Ausgabe",
        "rent.select_mode": "Auswählen",
        "rent.bulk_delete": "%d Zahlungen löschen?",
        "rent.bulk_delete_msg": "Diese Zahlungseinträge werden dauerhaft gelöscht.",
        "rent.monthly_overview": "Monatsübersicht",
        "rent.no_data": "Keine Zahlungsdaten",
        "rent.filter_contract": "Nach Vertrag filtern",
        "rent.filter_status": "Nach Status filtern",
        "rent.all_contracts": "Alle Verträge",
        "rent.select_contract": "Vertrag auswählen",
        "rent.contract_section": "Vertrag",
        "rent.period": "Zeitraum",
        "rent.month": "Monat",
        "rent.year": "Jahr",
        "rent.due_date": "Fälligkeitsdatum",
        "rent.payment_section": "Zahlung",
        "rent.amount": "Betrag (€)",
        "rent.status": "Status",
        "rent.amount_paid": "Bezahlter Betrag (€)",
        "rent.record_paid_date": "Zahlungsdatum erfassen",
        "rent.paid_on": "Bezahlt am",
        "rent.status.paid": "Bezahlt",
        "rent.status.pending": "Ausstehend",
        "rent.status.overdue": "Überfällig",
        "rent.status.partial": "Teilweise",
        "rent.record": "Erfassen",
        "rent.total_received": "Gesamt erhalten",

        // Payment history in apartment
        "apt.payment_history": "Zahlungsverlauf",

        // Export
        "export.title": "Bericht exportieren",
        "export.report_type": "Berichtstyp",
        "export.date_range": "Zeitraum",
        "export.from": "Von",
        "export.to": "Bis",
        "export.filters": "Filter",
        "export.all_apartments": "Alle Wohnungen",
        "export.all_statuses": "Alle Status",
        "export.format": "Format",
        "export.preview": "Vorschau",
        "export.export_file": "In Datei exportieren",
        "export.no_data": "Keine Daten zum Exportieren.",
        "export.export_failed": "Export fehlgeschlagen:",
        "export.success": "%d Zeilen nach %@ exportiert",
        "export.payment_records": "Zahlungsdatensätze",
        "export.more_rows": "weitere Zeilen",
        "export.type.payments": "Mietzahlungen",
        "export.type.tenant_ledger": "Mieter-Kontoauszug",
        "export.type.apartment_summary": "Wohnungsübersicht",
        "export.type.contract_overview": "Vertragsübersicht",

        // Export CSV headers
        "export.h.month": "Monat",
        "export.h.year": "Jahr",
        "export.h.tenant": "Mieter",
        "export.h.tenant_no": "Mieter-Nr.",
        "export.h.apartment": "Wohnung",
        "export.h.contract": "Vertrag",
        "export.h.amount_due": "Fälliger Betrag",
        "export.h.amount_paid": "Bezahlter Betrag",
        "export.h.status": "Status",
        "export.h.due_date": "Fälligkeitsdatum",
        "export.h.paid_date": "Zahlungsdatum",
        "export.h.notes": "Notizen",
        "export.h.total_due": "Gesamt fällig",
        "export.h.total_paid": "Gesamt bezahlt",
        "export.h.balance": "Saldo",
        "export.h.paid_count": "Bezahlt Anz.",
        "export.h.pending_count": "Ausstehend Anz.",
        "export.h.overdue_count": "Überfällig Anz.",
        "export.h.street": "Straße",
        "export.h.gate": "Stiege",
        "export.h.top": "Top",
        "export.h.city": "Stadt",
        "export.h.postal": "PLZ",
        "export.h.type": "Typ",
        "export.h.company": "Unternehmen",
        "export.h.category": "Kategorie",
        "export.h.direction": "Richtung",
        "export.h.rooms": "Zimmer",
        "export.h.area": "Fläche (m2)",
        "export.h.monthly_rent": "Monatsmiete",
        "export.h.active_tenants": "Aktive Mieter",
        "export.h.total_contracts": "Verträge gesamt",
        "export.h.total_received": "Zahlungen erhalten",
        "export.h.contract_no": "Vertragsnr.",
        "export.h.start_date": "Vertragsbeginn",
        "export.h.end_date": "Vertragsende",
        "export.h.deposit": "Kaution",
        "export.h.duration": "Laufzeit (Monate)",
        "export.h.payments_count": "Zahlungen Anz.",
        "export.h.has_pdf": "PDF vorhanden",

        // Dashboard
        "dash.title": "Übersicht",
        "dash.overview": "Übersicht",
        "dash.total_apartments": "Wohnungen gesamt",
        "dash.active_contracts": "Aktive Verträge",
        "dash.total_tenants": "Mieter gesamt",
        "dash.monthly_revenue": "Monatliche Einnahmen",
        "dash.revenue_chart": "Einnahmen (Letzte 6 Monate)",
        "dash.expiring_contracts": "Auslaufende Verträge",
        "dash.no_expiring": "Keine Verträge laufen demnächst ab.",
        "dash.recent_payments": "Letzte Zahlungen",
        "dash.no_payments": "Keine aktuellen Zahlungsaktivitäten.",
        "dash.occupancy": "Auslastung",
        "dash.no_apartments": "Noch keine Wohnungen",
        "dash.no_apartments_desc": "Registrieren Sie Wohnungen, um die Statusübersicht zu sehen.",
        "dash.alerts": "Hinweise & Nachverfolgung",
        "dash.company_performance": "Unternehmens-Performance",
        "dash.company_revenue": "%@ Einnahmen (Letzte 12 Monate)",
        "dash.contract_expires": "Vertrag %@ für %@ läuft am %@ aus",
        "dash.overdue_payment": "Überfällige Zahlung von %@ für %@",

        // Settings
        "settings.title": "Einstellungen",
        "settings.users": "Benutzerverwaltung",
        "settings.add_user": "Benutzer hinzufügen",
        "settings.edit_user": "Benutzer bearbeiten",
        "settings.delete_user": "Benutzer löschen",
        "settings.change_password": "Passwort ändern",
        "settings.username": "Benutzername",
        "settings.full_name": "Vollständiger Name",
        "settings.role": "Rolle",
        "settings.password": "Passwort",
        "settings.new_password": "Neues Passwort",
        "settings.confirm_password": "Passwort bestätigen",
        "settings.language": "Sprache",
        "settings.manage_access": "Verwalten Sie, wer auf diese App zugreifen kann.",
        "settings.select_user": "Benutzer auswählen, um Details anzuzeigen",
        "settings.you": "(Sie)",
        "settings.role_permissions": "Rolle & Berechtigungen",
        "settings.can_manage": "Verwaltet",
        "settings.member_since": "Mitglied seit",
        "settings.access_summary": "Zugangsübersicht",
        "settings.identity": "Identität",
        "settings.full_name_req": "Vollständiger Name *",
        "settings.username_req": "Benutzername *",
        "settings.password_req": "Passwort *",
        "settings.current_password": "Aktuelles Passwort",
        "settings.current_password_field": "Aktuelles Passwort",
        "settings.confirm_new": "Neues Passwort bestätigen",
        "settings.no_match": "Passwörter stimmen nicht überein",
        "settings.wrong_password": "Aktuelles Passwort ist falsch.",
        "settings.update": "Aktualisieren",
        "settings.cannot_delete": "Kann nicht gelöscht werden",
        "settings.cannot_undo": "Dies kann nicht rückgängig gemacht werden.",
        "settings.last_admin": "Dies ist der letzte Administrator. Befördern Sie einen anderen Benutzer zum Admin, bevor Sie diesen löschen.",
        "settings.perm.everything": "Alles",
        "settings.perm.apt_con_ten_pay": "Wohnungen, Verträge, Mieter, Zahlungen",
        "settings.perm.payments_only": "Nur Zahlungen",
        "settings.perm.manage_users": "Benutzer verwalten",
        "settings.perm.manage_apartments": "Wohnungen verwalten",
        "settings.perm.manage_contracts": "Verträge verwalten",
        "settings.perm.manage_tenants": "Mieter verwalten",
        "settings.perm.manage_payments": "Zahlungen verwalten",

        // CSV Import
        "csv.title": "Aus CSV / Excel importieren",
        "csv.company": "Unternehmen",
        "csv.apt_columns": "Wohnungsspalten",
        "csv.tenant_columns": "Mieterspalten",
        "csv.tenant_columns_desc": "Mieterspalten (optional — werden automatisch erstellt und verknüpft)",
        "csv.required_note": "Nur **Straße** ist erforderlich. Wenn Mieterspalten vorhanden sind, werden Mieter und aktiver Vertrag automatisch erstellt.",
        "csv.defaults": "Standardwerte für fehlende Daten",
        "csv.import_tenants": "Mieter aus CSV importieren und mit Wohnungen verknüpfen",
        "csv.choose_file": "CSV-Datei auswählen…",
        "csv.download_sample": "Beispiel-CSV herunterladen",
        "csv.change_file": "Datei ändern",
        "csv.rows_found": "Zeilen gefunden",
        "csv.delimiter": "Trennzeichen",
        "csv.import_now": "Jetzt importieren",
        "csv.import_complete": "Import abgeschlossen",
        "csv.apartments_imported": "Wohnungen importiert",
        "csv.tenants_imported": "Mieter mit Verträgen erstellt",
        "csv.import_another": "Weiteren Import",
        "csv.preview": "Vorschau",
        "csv.panel_message": "Wählen Sie eine CSV-Datei aus Excel",
        "csv.panel_prompt": "Importieren",
        "csv.error.read": "Datei konnte nicht gelesen werden. Speichern Sie als UTF-8 CSV aus Excel.",
        "csv.error.empty": "Datei ist leer.",
        "csv.error.rows": "CSV benötigt mindestens eine Kopfzeile und eine Datenzeile.",
        "csv.duplicates_skipped": "%d Duplikate übersprungen",
        "csv.duplicate_skip": "Überspringen",
        "csv.duplicate_update": "Aktualisieren",
        "csv.resolve_duplicates": "Duplikate auflösen",
        "csv.skip_all": "Alle überspringen",
        "csv.update_all": "Alle aktualisieren",
        "csv.conflict_count": "%d Duplikat(e) gefunden",
        "csv.confirm_import": "Import bestätigen",
        "csv.contract_category": "Vertragsart",

        // Sync
        "settings.sync": "Synchronisation",
        "settings.sync.active": "iCloud-Sync aktiv",
        "settings.sync.inactive": "iCloud nicht verfügbar",
        "settings.sync.location": "Speicherort",

        // Login
        "login.title": "Immobilienverwaltung",
        "login.subtitle": "Melden Sie sich an, um Ihre Immobilien zu verwalten",
        "login.username": "Benutzername",
        "login.password": "Passwort",
        "login.sign_in": "Anmelden",
        "login.invalid": "Ungültiger Benutzername oder Passwort.",
        "login.sign_out": "Abmelden",
        "login.default_creds": "Standard-Anmeldedaten: admin / admin123",
    ]
}

// MARK: - Environment Key

struct LocalizationKey: EnvironmentKey {
    static let defaultValue = LocalizationManager()
}

extension EnvironmentValues {
    var loc: LocalizationManager {
        get { self[LocalizationKey.self] }
        set { self[LocalizationKey.self] = newValue }
    }
}
